export { Hero } from './Hero'
export { Features } from './Features'
export { CTA } from './CTA'
export { Testimonials } from './Testimonials'
export { Pricing } from './Pricing'
export { FAQ } from './FAQ'